version: '2'
services:
  contact_list_web:
    build: .
    entrypoint: /var/app/entrypoint.sh
    volumes:
      - .:/var/app
    ports:
      - "8080:8080"
    depends_on:
      - db

    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD:
      DB_HOST: db
      DB_HOST_READ_REPLICA: db
      DB_PORT: 5432
      DATABASE_URL: postgres://postgres:@db:5432/postgres

  db:
    image: postgres:9.6.6-alpine
    volumes:
      - contact_list_postgres:/var/lib/postgresql/data

volumes:
  contact_list_postgres:
